server:
#  port: 8081
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/wallet}


spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:169.56.174.138}:${DB_PORT:31922}/${DB_NAME:wallet}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:passw0rd}
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:169.56.174.138}:${KAFKA_BROKER_PORT:31278}
    listener.ack-mode: MANUAL_IMMEDIATE
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${CONSUMER_GROUP:naksam-consumer-group}
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

bootcamp:
  club:
    topic: ${WALLET_TOPIC:naksam-club-join}